name: Test Pays

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_pays:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Start server
      run: |
        Start-Process -FilePath "python" -ArgumentList "expose_py.py" -PassThru
        Start-Sleep -Seconds 5  

    - name: Check if server is running
      run: Get-Process python

    - name: Vérification API
      run: |
        # Définir l'URL de l'API pour la France
        $url = "https://restcountries.com/v3.1/name/France"

        # Faire la requête GET pour récupérer les données JSON
        $response = Invoke-RestMethod -Uri $url -Method Get

        # Afficher la réponse JSON dans le terminal
        $response | ConvertTo-Json -Depth 3

    - name: Test pays France
      run: |
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:5001/soumettre" -Method POST -Body "pays=France" -ContentType "application/x-www-form-urlencoded"
        Write-Output "Response: $($response.Content)"

    - name: Stop server
      run: |
        Stop-Process -Name "python" -Force
